# Generated by Django 4.2.3 on 2024-02-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('energy', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('protien', models.FloatField()),
                ('fat', models.FloatField()),
                ('sugar', models.FloatField()),
                ('health_score', models.FloatField()),
            ],
        ),
    ]
