# Generated by Django 4.2.5 on 2024-02-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_userprofile_dob_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.FloatField(choices=[(1.55, 'Sedentary'), (1.85, 'Moderately active'), (2.2, 'Vigorously active'), (2.4, 'Extremely active')], default=1.85, max_length=20),
        ),
    ]
